environment:
  class: NADEWithAV
  module: terasim_nde_nade.envs
  parameters:
    AV_cfg:
      cache_radius: 100
      control_radius: 50
      initial_lane_index: 0
      initial_lane_position: 0.0
      initial_speed: 30.0
      clearance_distance: 50
      type: vehicle_passenger
    MOBIL_lc_flag: true
    adversity_cfg:
      vehicle:
        highway_cutin:
          _target_: terasim_nde_nade.adversity.vehicles.lanechange_adversity.LanechangeAdversity
          _convert_: 'all'
          location: 'highway'
          ego_type: 'vehicle'
          probability: 3.1996225726187704e-05
          predicted_collision_type: "highway_cutin" 
    adversity_sampling_probability: 0.1
    drive_rule: righthand
    info_extractor: terasim.logger.infoextractor.InfoExtractor
    log_flag: true
    run_time: 1200
    stochastic_acc_flag: false
    vehicle_factory: terasim_nde_nade.vehicle.nde_vehicle_factory.NDEVehicleFactory
    warmup_time_lb: 749
    warmup_time_ub: 750
input:
  sumo_config_file: examples/texas_highway_maps/2/simulation.sumocfg
  sumo_net_file: examples/texas_highway_maps/2/map.net.xml
logging:
  levels:
  - TRACE
  - INFO
output:
  aggregated_dir: aggregated
  dir: outputs
  name: cutin
  nth: 000_53688
seed: 12345
simulator:
  class: Simulator
  module: terasim.simulator
  parameters:
    gui_flag: false  # Enable GUI to see the construction zone
    num_tries: 10
    realtime_flag: false
    sumo_output_file_types:
    - collision
    - tripinfo
    sumo_seed: 29451