environment:
  class: NADEWithAV
  module: terasim_nde_nade.envs
  parameters:
    CAV_cfg:
      cache_radius: 100
      control_radius: 50
      initial_lane_index: 0
      initial_lane_position: 0.0
      initial_speed: 20.0
      type: vehicle_passenger
    MOBIL_lc_flag: true
    adversity_cfg:
      static:
        stalled_object:
          _convert_: all
          _target_: terasim_nde_nade.adversity.StalledObjectAdversity
          end_time: 1200
          lane_id: '1202002183_1'
          lane_position: 245.0
          object_type: vehicle_passenger
          start_time: 700
    adversity_sampling_probability: 0.1
    drive_rule: righthand
    info_extractor: terasim.logger.infoextractor.InfoExtractor
    log_flag: true
    run_time: 1200
    stochastic_acc_flag: false
    vehicle_factory: terasim_nde_nade.vehicle.nde_vehicle_factory.NDEVehicleFactory
    warmup_time_lb: 749
    warmup_time_ub: 750
input:
  sumo_config_file: /home/mtl/Bot-Auto-Demo/examples/bot_map/0/sumo_medium.sumocfg
  sumo_net_file: /home/mtl/Bot-Auto-Demo/examples/bot_map/0/map.net.xml
logging:
  levels:
  - TRACE
  - INFO
output:
  aggregated_dir: aggregated
  dir: output_folder
  name: test
  nth: '0_0'
simulator:
  class: Simulator
  module: terasim.simulator
  parameters:
    gui_flag: true
    num_tries: 10
    realtime_flag: false
    sumo_output_file_types:
    - fcd_all
    - collision
    - tripinfo
