adversity_cfg:
  vehicle:
    highway_cutin_abort:
      _target_: terasim_nde_nade.adversity.vehicles.lanechangeabort_adversity.LanechangeAbortAdversity
      _convert_: 'all'
      location: 'highway'
      ego_type: 'vehicle'
      probability: 1e-5
      predicted_collision_type: "highway_cutin" 