version: '3.8'

services:
  terasim_service:
    image: public.ecr.aws/x0u0p9b6/terasim/service:1.0.0-cpu
    container_name: terasim_service
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    volumes:
      - ../examples:/app/examples
    command: ["/bin/bash", "examples/main_cosim.sh"]
    depends_on:
      - mcity_carla

  mcity_carla:
    image: public.ecr.aws/x0u0p9b6/mcity-digital-twin:0.9.15
    container_name: mcity_carla
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: ["/bin/bash", "./CarlaUE4.sh"]