# TeraSim Simulation Configuration

# Output settings
output:
  dir: "output"  # Output directory
  name: "simulation"  # Experiment name
  nth: "1"  # Experiment number
  aggregated_dir: "logs"  # Directory for aggregated logs

# Environment configuration
environment:
  module: "terasim_nde_nade.envs.safetest_nade"
  class: "SafeTestNADE"
  parameters:
    vehicle_factory: "terasim_nde_nade.vehicle.nde_vehicle_factory.NDEVehicleFactory"
    info_extractor: "terasim.logger.infoextractor.InfoExtractor"
    log_flag: true
    warmup_time_lb: 10  # Lower bound for warmup time
    warmup_time_ub: 20  # Upper bound for warmup time
    run_time: 3600  # Simulation run time

# Simulator configuration
simulator:
  module: "terasim.simulator"
  class: "Simulator"
  parameters:
    num_tries: 10
    gui_flag: false  # Default to headless mode
    realtime_flag: false
    sumo_output_file_types: 
      - "fcd_all"
      - "collision"
      - "tripinfo"

# File paths (relative to maps directory)
file_paths:
  sumo_net_file: "town10/town10.net.xml"
  sumo_config_file: "town10/town10.sumocfg"

# Logging configuration
logging:
  levels:
    - "TRACE"  # Log level for the main log file
    - "INFO"   # Log level for the aggregated log file 