adversity_cfg:
  vulnerable_road_user:
    stopcrossing:
      _target_: terasim_nde_nade.adversity.vru.stopcrossing_adversity.StopCrossingAdversity
      _convert_: 'all'
      location: 'crosswalk'
      ego_type: 'vulnerable_road_user'
      probability: 0.1
      predicted_collision_type: "intersection_stopcrossing"