adversity_cfg:
  vulnerable_road_user:
    jaywalking:
      _target_: terasim_nde_nade.adversity.vru.jaywalking_adversity.JaywalkingAdversity
      _convert_: 'all'
      location: 'crosswalk'
      ego_type: 'vulnerable_road_user'
      probability: 0.1
      predicted_collision_type: "intersection_jaywalking"