environment:
  # Module containing the environment class
  module: "terasim_nde_nade.envs"  # Use "terasim_nde_nade.envs.safetest_nade" for non-AV simulations
  # Environment class name
  class: "NADEWithAV"  # Use "SafeTestNADE" for non-AV simulations
  parameters:
    # Vehicle factory class
    vehicle_factory: "terasim_nde_nade.vehicle.nde_vehicle_factory.NDEVehicleFactory"
    # Info extractor class
    info_extractor: "terasim.logger.infoextractor.InfoExtractor"
    log_flag: true
    warmup_time_lb: 749  # Lower bound for warmup time
    warmup_time_ub: 750  # Upper bound for warmup time
    run_time: 1200  # Simulation run time (use 30 for non-AV simulations)

    MOBIL_lc_flag: True
    stochastic_acc_flag: False
    drive_rule: "righthand"

    adversity_sampling_probability: 0.1 