adversity_cfg:
  vehicle:
    highway_rearend_decel:
      _target_: terasim_nde_nade.adversity.vehicles.FollowerAdversity
      _convert_: 'all'
      location: 'highway'
      ego_type: 'vehicle'
      probability: 1e-5
      predicted_collision_type: "highway_rearend" 