adversity_cfg:
  vehicle:
    intersection_rearend:
      _target_: terasim_nde_nade.adversity.vehicles.leader_adversity.LeaderAdversity
      _convert_: 'all'
      location: 'intersection'
      ego_type: 'vehicle'
      probability: 0.00017365940078885788
      predicted_collision_type: "intersection_rearend" 